fprintf(1,'Executing %s at %s:\n',mfilename(),datestr(now));
ver,
try,
addpath('/home/jibril/spm12');

        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

        jobs{1}.spm.spatial.realign.estwrite.eoptions.fwhm = 5.0;
jobs{1}.spm.spatial.realign.estwrite.eoptions.sep = 4.0;
jobs{1}.spm.spatial.realign.estwrite.eoptions.interp = 2;
jobs{1}.spm.spatial.realign.estwrite.eoptions.rtm = 1;
jobs{1}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
jobs{1}.spm.spatial.realign.estwrite.eoptions.wrap(1) = 0;
jobs{1}.spm.spatial.realign.estwrite.eoptions.wrap(2) = 0;
jobs{1}.spm.spatial.realign.estwrite.eoptions.wrap(3) = 0;
jobs{1}.spm.spatial.realign.estwrite.data = {...
{...
'/home/jibril/.populse_projects/projects/test_bug46/data/raw_data/tM0_MAP-VS-704-599566309-2019-04-05_09-39-09-0-SOURCE_-_3D_pCASL_FOV_FH125_dynstab_regular-SOURCE_-_3D_pCASL_FOV_FH125_dynstab_regular-.nii,1';...
'/home/jibril/.populse_projects/projects/test_bug46/data/raw_data/tM0_MAP-VS-704-599566309-2019-04-05_09-39-09-0-SOURCE_-_3D_pCASL_FOV_FH125_dynstab_regular-SOURCE_-_3D_pCASL_FOV_FH125_dynstab_regular-.nii,2';...
};
};
jobs{1}.spm.spatial.realign.estwrite.roptions.prefix = 'r';
jobs{1}.spm.spatial.realign.estwrite.roptions.which(1) = 0;
jobs{1}.spm.spatial.realign.estwrite.roptions.which(2) = 1;
jobs{1}.spm.spatial.realign.estwrite.roptions.mask = 1;

        spm_jobman('run', jobs);

        
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;